
[theme]
	hide_image = false
	border_color = "255,1,165,82"
	title_color = "255,255,255,255"
	title_font = 0
	artist_color = "255,255,255,255"
	artist_font = 0
	background_color = "80,0,0,0"

	[theme.progress_bar]
		background_color = "255,50,50,50"
		color = "255,255,255,255"
		number_color = "255,255,255,255"
		radius = 3.0
		font = 0

	[theme.controls]
		color = "255,255,255,255"
		hover_color = "255,150,150,150"
		selected_color = "255,1,165,82"
		selected_hover_color = "255,0,212,105"

	[theme.icons]
		settings = "https://files.teamresourceful.com/r/9DzwrP.png"
		show_settings_button = true
		shuffle = "https://files.teamresourceful.com/r/Bl9ZTS.png"
		show_shuffle_button = true
		previous = "https://files.teamresourceful.com/r/Dr7nH1.png"
		show_previous_button = true
		pause = "https://files.teamresourceful.com/r/55kubx.png"
		play = "https://files.teamresourceful.com/r/rlQyJs.png"
		"show_play/pause_toggle" = true
		next = "https://files.teamresourceful.com/r/FDIAxt.png"
		show_next_button = true
		repeat = "https://files.teamresourceful.com/r/4gVqmu.png"
		show_repeat_button = true
		external_link = "https://files.teamresourceful.com/r/7gJ4OY.png"
		show_external_link_button = true
		volume_control = "https://files.teamresourceful.com/r/i7XLC1.png"
		show_volume_control_button = true
		position_editor = "https://files.teamresourceful.com/r/N3c8xm.png"
		show_position_editor_button = true

