# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				sheep = true
				rabbit = true
				pig = true
				cow = true
				squid = true
				cod = true
				spider = true
				glow_squid = true
				skeleton = true
				creeper = true
				zombie = true
				bat = true
				witch = true
				enderman = true
				salmon = true
				item = true
				chicken = true
				drowned = true
				arrow = true
				villager = true
				iron_golem = true
				horse = true
				cat = true
				bee = true
				tnt_minecart = true
				cave_spider = true
				zombie_villager = true
				fox = true
				axolotl = true
				donkey = true
				pufferfish = true
				tropical_fish = true
				dolphin = true

			[light_sources.settings.entities.naturalist]
				coral_snake = true
				boar = true
				lizard = true
				bear = true
				bass = true
				firefly = true
				snail = true
				deer = true
				cardinal = true
				duck = true
				robin = true
				rhino = true
				lion = true
				elephant = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.promenade]
				lush_creeper = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

