blacklistedOres = []
enableNoEmiMessage = true
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = true
enableAe2Integration = true
enableFtbQuestsIntegration = true
generateOres = false
datagenOnStartup = false
loadRuntimeGeneratedResources = false
removeIndustrialistTrades = true
maxDistillationTowerHeight = 9
